import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  FRONTEND_URL: Joi.string().uri().default('http://localhost:5173'),
  CORS_ORIGINS: Joi.string().default('http://localhost:5173'),
  DATABASE_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(8).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_SECRET: Joi.string().min(8).required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  OAUTH_EXCHANGE_SECRET: Joi.string().min(8).optional(),
  REFRESH_TOKEN_DELIVERY: Joi.string().valid('body', 'cookie').default('body'),
  BCRYPT_ROUNDS: Joi.number().min(4).max(15).default(10),
  BOOTSTRAP_ADMIN_EMAIL: Joi.string().email().default('admin@example.com'),
  BOOTSTRAP_ADMIN_PASSWORD: Joi.string().min(8).default('Admin123!'),
  REQUIRE_EMAIL_VERIFICATION: Joi.string().valid('true', 'false').default('false'),
  EMAIL_ENABLED: Joi.string().valid('true', 'false').default('true'),
  SMTP_HOST: Joi.string().default('localhost'),
  SMTP_PORT: Joi.number().default(1025),
  SMTP_USER: Joi.string().allow('').default(''),
  SMTP_PASS: Joi.string().allow('').default(''),
  SMTP_SECURE: Joi.string().valid('true', 'false').default('false'),
  EMAIL_FROM: Joi.string().email().default('noreply@example.com'),
  GOOGLE_OAUTH_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GOOGLE_CLIENT_ID: Joi.string().allow('').default(''),
  GOOGLE_CLIENT_SECRET: Joi.string().allow('').default(''),
  GOOGLE_CALLBACK_URL: Joi.string().uri().allow('').default(''),
  GITHUB_OAUTH_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GITHUB_CLIENT_ID: Joi.string().allow('').default(''),
  GITHUB_CLIENT_SECRET: Joi.string().allow('').default(''),
  GITHUB_CALLBACK_URL: Joi.string().uri().allow('').default(''),
  STRIPE_ENABLED: Joi.string().valid('true', 'false').default('false'),
  STRIPE_SECRET_KEY: Joi.string().allow('').default(''),
  STRIPE_WEBHOOK_SECRET: Joi.string().allow('').default(''),
  STRIPE_SUCCESS_URL: Joi.string().uri().default(
    'http://localhost:5173/billing/success',
  ),
  STRIPE_CANCEL_URL: Joi.string().uri().default(
    'http://localhost:5173/billing/cancel',
  ),
  THROTTLE_TTL: Joi.number().default(60000),
  THROTTLE_LIMIT: Joi.number().default(10),
  RUN_SEED: Joi.string().valid('true', 'false').default('false'),
});
